### POST request to example server
POST http://localhost:8081/public/user/account/reset/password/redirex
Content-Type: application/json

{
    "resetSessionToken": "26b8b995-ccca-4db1-a3ec-421fe12ece02",
    "newPassword": "Felipe@10203040"
}