### POST request create user
POST http://localhost:8081/public/auth/v1/user/register
Content-Type: application/json

{
  "fullname": "felipepanosso",
  "email": "felipepanosso21@gmail.com",
  "password": "123456784fe",
  "occupation": "gerente",
  "cpf": "13042799954",
  "phone": "448991805405"
}

###