### POST request create address
POST http://localhost:8081/api/user/address/b14ef7b1-c460-4a5d-bb6c-cdf0dbecd736/create/address
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VySWQiOiJiMTRlZjdiMS1jNDYwLTRhNWQtYmI2Yy1jZGYwZGJlY2Q3MzYiLCJlbWFpbCI6ImZlbGlwZXBhbm9zc28yMUBnbWFpbC5jb20iLCJzdWIiOiJmZWxpcGVwYW5vc3NvMjFAZ21haWwuY29tIiwiaWF0IjoxNzYwODE5NjMyLCJleHAiOjE4NDcyMTk2MzJ9.hQ4cjHiSvDniiQbWbICJNeFNkCcr_bkUdVvnHtmhfX1LoPmt53VECu3vNR3hqKdFAn6D1AxR1PFhTK6WfhyJyA

{
  "userId": "b14ef7b1-c460-4a5d-bb6c-cdf0dbecd736",
  "recipientName": "felipe panosso",
  "country": "Brasil",
  "state": "Parana",
  "city": "Maringa",
  "street": "Avenida Lucio de Held",
  "zipcode": "87033230",
  "phone": "44991805405",
  "residenceType": "",
  "complement": ""
}
###