### POST request create order
POST http://localhost:8081/private/v1/api/users/ec3c0370-185f-42ff-b4d7-24b278b7de57/create/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VySWQiOiJlYzNjMDM3MC0xODVmLTQyZmYtYjRkNy0yNGIyNzhiN2RlNTciLCJzdWIiOiJmZWxpcGVwYW5vc3NvMjFAZ21haWwuY29tIiwiaWF0IjoxNzU1NTQwNTM4LCJleHAiOjE4NDE5NDA1Mzh9.XQik0oQLWEo_TgG3LxQ0AI0ZVr4UNRoPlT8MeVDTxhQdtAy_-ZZcPEGQsAch5aKaVu5Dzpc2qCPTfefiEskFnA

{
  "userId": "ec3c0370-185f-42ff-b4d7-24b278b7de57",
  "warehouseId": "e8d36fea-9aa7-4bf3-82cc-8bc9f3fc9742",
  "description": "DT Batch J1",
  "productUrl": "https://shop1802721248.v.weidian.com/item.html?itemID=7304860125&spider_token=c6b0",
  "quantity": 1,
  "size": 43.5,
  "recipientCpf": "13042799954",
  "productCategoryId": "fd3a847f-d6cf-4cfc-8305-e9cb3ffa72d1",
  "autoFetchPrice": true
}

###