### POST request payment order
POST http://localhost:8081/private/v1/api/users/ec3c0370-185f-42ff-b4d7-24b278b7de57/orders/d456de4c-f739-42ea-88d2-647d186247b8/payment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VySWQiOiJlYzNjMDM3MC0xODVmLTQyZmYtYjRkNy0yNGIyNzhiN2RlNTciLCJzdWIiOiJmZWxpcGVwYW5vc3NvMjFAZ21haWwuY29tIiwiaWF0IjoxNzU1NTQwNTM4LCJleHAiOjE4NDE5NDA1Mzh9.XQik0oQLWEo_TgG3LxQ0AI0ZVr4UNRoPlT8MeVDTxhQdtAy_-ZZcPEGQsAch5aKaVu5Dzpc2qCPTfefiEskFnA

{
  "userId": "ec3c0370-185f-42ff-b4d7-24b278b7de57",
  "orderId": "d456de4c-f739-42ea-88d2-647d186247b8"
}

###